name: lab4

on:
 push:
  branches: [master]
  pull_request: [master]

jobs:
 Build: 
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ubuntu-latest, windows-latest]
  steps: 
  - uses: actions/checkout@v3
   
  - name: Solver
    run: |
     cmake . -B build/gcc -DCMAKE_CXX_COMPILER=g++
     cmake --build build/gcc
     cmake . -B build/clang -DCMAKE_CXX_COMPILER=clang++
     cmake --build build/clang
