name: lab4

on:
 push:
  branches: [master]
  pull_request: [master]

jobs:
 Linux: 
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/checkout@v3
   
  - name: Solver
    run: |
     cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build
     cmake --build ${{github.workspace}}/solver_application/build
   
  - name: Hello_world
    run: |
     cmake ${{github.workspace}}/hello_world__application/ -B ${{github.workspace}}/hello_world_application/build 
     cmake --build ${{github.workspace}}/hello_world_application/build  
 
 Windows:
  runs-on: windows-latest
  steps:
  - uses: actions/checkout@v3
    
  - name: Solver
    run: |
     cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build 
     cmake --build ${{github.workspace}}/solver_application/build 
   
  - name: Hello_world
    run: |
     cmake ${{github.workspace}}/hello_world__application/ -B ${{github.workspace}}/hello_world_application/build 
     cmake --build ${{github.workspace}}/hello_world_application/build  


